package com.example.smashrun.models;

import java.util.Date;
import java.util.List;

public class SmashRunActivity {
    public int activityId;
    public String activityType;
    public double duration;
    public double distance;
    public int calories;
    public String notes;
    public Date startDateTimeLocal;
    public String externalId;
    public String source;
    public String appVersion;
    public String deviceType;
    public int hasDetails;
    public int hasDetailsGPS;
    public double startLatitude;
    public double startLongitude;
    public int heartRateMax;
    public int heartRateMin;
    public int heartRateAverage;
    public int cadenceMax;
    public int cadenceMin;
    public int cadenceAverage;
    public String weatherType;
    public double temperature;
    public int humidity;
    public int windSpeed;
    public double temperatureApparent;
    public double temperatureWindChill;
    public String howFelt;
    public String terrain;
    public int isRace;
    public int isTreadmill;
    public int isBadHR;
    public int isBadElevation;
    public Date syncDateTimeUTC;
    public Date dateCreatedUTC;
    public Date dateUpdatedUTC;
    public List<String> recordingKeys;
    public List<List<Integer>> recordingValues;
    public List<Object> pauseIndexes;
    public List<SmashRunLap> laps;
    public Object songs;
    public Object heartRateRecovery;
    public double speedVariability;
    public Date sunriseLocal;
    public Date sunsetLocal;
    public double moonPhase;
    public int elevationGain;
    public int elevationLoss;
    public int elevationAscent;
    public int elevationDescent;
    public int elevationMin;
    public int elevationNet;
    public String countryCode;
    public String country;
    public String city;
    public String state;
    public int isCooperTest;
}
